import type {
  GenerateInstructionsInput,
  GenerateInstructionsOutput,
  InstructionFileKind,
  DetectedProjectInfo,
} from "../types/index.js";
import { instructionKindToPath } from "../utils/instructionKinds.js";

export function generateInstructions(
  input: GenerateInstructionsInput,
): GenerateInstructionsOutput {
  const proj = input.detectedProject;
  const kind = input.targetKind;

  let content: string;
  switch (kind) {
    case "agents":
      content = generateAgents(proj);
      break;
    case "claude":
      content = generateClaude(proj);
      break;
    case "cursor":
      content = generateCursor(proj);
      break;
    case "copilot":
      content = generateCopilot(proj);
      break;
    case "roo":
      content = generateRoo(proj);
      break;
    default:
      content = generateAgents(proj);
  }

  const suggestedPath = instructionKindToPath(kind);
  const targetPath = `${input.rootDir}/${suggestedPath}`;

  return { content, targetPath, suggestedPath };
}

function generateAgents(proj: DetectedProjectInfo): string {
  const lines: string[] = [];

  lines.push("# Project Agent Guide");
  lines.push("");
  lines.push("<!-- Generated by ContextKit. Review and customize before using. -->");
  lines.push("");

  // Overview
  lines.push("## Project Overview");
  lines.push("");
  if (proj.frameworks.length > 0) {
    lines.push(`- Framework: ${proj.frameworks.join(", ")}`);
  }
  if (proj.languages.length > 0) {
    lines.push(`- Language: ${proj.languages.join(", ")}`);
  }
  if (proj.packageManager) {
    lines.push(`- Package manager: ${proj.packageManager}`);
  }
  if (proj.testTools.length > 0) {
    lines.push(`- Tests: ${proj.testTools.join(", ")}`);
  }
  if (proj.lintTools.length > 0) {
    lines.push(`- Linting: ${proj.lintTools.join(", ")}`);
  }
  if (proj.formatTools.length > 0) {
    lines.push(`- Formatting: ${proj.formatTools.join(", ")}`);
  }
  lines.push("");

  // Commands
  if (proj.buildCommands.length > 0) {
    lines.push("## Commands");
    lines.push("");
    const installCmd = getInstallCommand(proj.packageManager);
    lines.push(`- Install: \`${installCmd}\``);
    for (const cmd of proj.buildCommands) {
      lines.push(`- ${cmd}`);
    }
    lines.push("");
  }

  // Tests
  if (proj.testCommands.length > 0) {
    lines.push("## Testing Commands");
    lines.push("");
    for (const cmd of proj.testCommands) {
      lines.push(`- ${cmd}`);
    }
    lines.push("");
  }

  // Coding standards
  lines.push("## Coding Standards");
  lines.push("");
  lines.push("<!-- ContextKit: verify these conventions match your project -->");
  lines.push("");
  if (proj.lintTools.length > 0) {
    lines.push(`- Follow ${proj.lintTools.join(" and ")} rules.`);
  }
  if (proj.formatTools.length > 0) {
    lines.push(`- Code is formatted using ${proj.formatTools.join(" and ")}.`);
  }
  if (proj.languages.includes("TypeScript")) {
    lines.push("- Use strict TypeScript types. Avoid `any`.");
    lines.push("- Export types alongside their implementations.");
  }
  lines.push("");

  // Testing rules
  lines.push("## Testing Rules");
  lines.push("");
  if (proj.testTools.length > 0) {
    lines.push(`- Write tests using ${proj.testTools.join(" and ")}.`);
    lines.push("- Run tests before committing changes.");
  } else {
    lines.push("- Write tests for new features and bug fixes.");
    lines.push("- Run tests before committing changes.");
  }
  lines.push("");

  // Security
  lines.push("## Security Rules");
  lines.push("");
  lines.push("- Never commit secrets, API keys, or credentials.");
  lines.push("- Validate user input on both client and server.");
  lines.push("- Keep dependencies updated.");
  lines.push("");

  // Infrastructure
  if (proj.hasDocker || proj.hasCi) {
    lines.push("## Infrastructure");
    lines.push("");
    if (proj.hasDocker) {
      lines.push("- Project uses Docker. See Dockerfile and docker-compose.yml.");
    }
    if (proj.hasCi) {
      lines.push("- CI/CD is configured. Check workflow files for pipeline details.");
    }
    lines.push("");
  }

  // Database
  if (proj.hasDatabaseMigrations) {
    lines.push("## Database");
    lines.push("");
    lines.push("- Database migrations are used. Run migrations before testing.");
    lines.push("- Do not modify existing migration files.");
    lines.push("");
  }

  // File map
  lines.push("## File Map");
  lines.push("");
  lines.push("<!-- ContextKit: add key file paths -->");
  lines.push("");
  lines.push("- Source code: `src/`");
  lines.push("- Tests: `test/` or `__tests__/`");
  if (proj.hasDocker) {
    lines.push("- Docker config: `Dockerfile`, `docker-compose.yml`");
  }
  if (proj.hasCi) {
    lines.push("- CI workflows: `.github/workflows/`");
  }
  lines.push("");

  // Known constraints
  lines.push("## Known Constraints");
  lines.push("");
  lines.push("<!-- ContextKit: document any known constraints or limitations -->");
  lines.push("");

  return lines.join("\n");
}

function generateClaude(proj: DetectedProjectInfo): string {
  const lines: string[] = [];

  lines.push("# CLAUDE.md");
  lines.push("");
  lines.push("<!-- Generated by ContextKit. Review and customize before using. -->");
  lines.push("");

  lines.push("## Project Context");
  lines.push("");

  if (proj.frameworks.length > 0) {
    lines.push(`This is a ${proj.frameworks.join(", ")} project using ${proj.languages.join(", ")}.`);
  }

  if (proj.packageManager) {
    const installCmd = getInstallCommand(proj.packageManager);
    lines.push(`Install dependencies with \`${installCmd}\`.`);
  }

  if (proj.buildCommands.length > 0) {
    lines.push("Build commands:");
    for (const cmd of proj.buildCommands) {
      lines.push(`- \`${cmd}\``);
    }
  }

  if (proj.testCommands.length > 0) {
    lines.push("Test commands:");
    for (const cmd of proj.testCommands) {
      lines.push(`- \`${cmd}\``);
    }
  }

  lines.push("");
  lines.push("## Rules");
  lines.push("");
  lines.push("- Follow the coding standards defined in the project.");
  lines.push("- Never commit secrets.");
  lines.push("- Write tests for new code.");

  return lines.join("\n");
}

function generateCursor(proj: DetectedProjectInfo): string {
  const lines: string[] = [];

  lines.push("---");
  lines.push("description: Project rules for Cursor IDE");
  lines.push("globs:");
  lines.push('  - "**/*"');
  lines.push("alwaysApply: true");
  lines.push("---");
  lines.push("");
  lines.push("# Project Rules");
  lines.push("");

  if (proj.frameworks.length > 0) {
    lines.push(`This is a ${proj.frameworks.join("/")} project.`);
    lines.push("");
  }

  const installCmd = getInstallCommand(proj.packageManager);
  lines.push(`Install: \`${installCmd}\``);

  if (proj.buildCommands.length > 0) {
    for (const cmd of proj.buildCommands) {
      lines.push(`${cmd}`);
    }
  }

  if (proj.testCommands.length > 0) {
    lines.push("");
    lines.push("## Testing");
    for (const cmd of proj.testCommands) {
      lines.push(`- ${cmd}`);
    }
  }

  lines.push("");
  lines.push("## Coding Rules");
  lines.push("- Follow project conventions.");
  lines.push("- Never commit secrets.");
  lines.push("- Write tests for new code.");

  return lines.join("\n");
}

function generateCopilot(proj: DetectedProjectInfo): string {
  const lines: string[] = [];

  lines.push("# GitHub Copilot Instructions");
  lines.push("");
  lines.push("<!-- Generated by ContextKit. Review and customize before using. -->");
  lines.push("");

  if (proj.frameworks.length > 0) {
    lines.push(`This is a ${proj.frameworks.join(", ")} project built with ${proj.languages.join(", ")}.`);
    lines.push("");
  }

  lines.push("## Commands");
  lines.push("");
  const installCmd = getInstallCommand(proj.packageManager);
  lines.push(`- Install: \`${installCmd}\``);

  if (proj.buildCommands.length > 0) {
    for (const cmd of proj.buildCommands) {
      lines.push(`- ${cmd}`);
    }
  }

  if (proj.testCommands.length > 0) {
    lines.push("");
    lines.push("## Testing");
    for (const cmd of proj.testCommands) {
      lines.push(`- ${cmd}`);
    }
  }

  lines.push("");
  lines.push("## Important");
  lines.push("- Follow existing code patterns in the repository.");
  lines.push("- Never commit secrets or credentials.");
  lines.push("- Write tests for new features.");

  return lines.join("\n");
}

function generateRoo(proj: DetectedProjectInfo): string {
  const lines: string[] = [];

  lines.push("# Roo Project Rules");
  lines.push("");
  lines.push("<!-- Generated by ContextKit. Review and customize before using. -->");
  lines.push("");

  if (proj.frameworks.length > 0) {
    lines.push(`## Tech Stack`);
    lines.push("");
    lines.push(`- Framework: ${proj.frameworks.join(", ")}`);
    lines.push(`- Language: ${proj.languages.join(", ")}`);
    if (proj.packageManager) {
      lines.push(`- Package manager: ${proj.packageManager}`);
    }
    lines.push("");
  }

  if (proj.buildCommands.length > 0) {
    lines.push("## Commands");
    lines.push("");
    for (const cmd of proj.buildCommands) {
      lines.push(`- ${cmd}`);
    }
    lines.push("");
  }

  lines.push("## Rules");
  lines.push("");
  lines.push("- Follow project conventions.");
  lines.push("- Never commit secrets.");
  lines.push("- Write tests for new code.");

  return lines.join("\n");
}

function getInstallCommand(pm: DetectedProjectInfo["packageManager"]): string {
  switch (pm) {
    case "pnpm": return "pnpm install";
    case "yarn": return "yarn install";
    case "bun": return "bun install";
    default: return "npm install";
  }
}
