import type { SkillGroupDefinition } from "../types/index.js";

export const SKILL_GROUPS: SkillGroupDefinition[] = [
  {
    id: "core",
    label: "Core Engineering",
    skills: [
      "typescript-strict",
      "code-review",
      "refactor-safe",
      "bugfix-systematic",
      "testing-strategy",
      "security-review",
      "documentation",
      "error-handling",
      "logging-observability",
      "repo-health-check",
    ],
  },
  {
    id: "frontend",
    label: "Frontend",
    skills: [
      "react-ui",
      "nextjs-app-router",
      "tailwind-ui",
      "accessibility-a11y",
      "frontend-performance",
      "forms-validation",
      "design-system",
      "responsive-layouts",
      "dashboard-ui",
      "webview-ui",
    ],
  },
  {
    id: "backend",
    label: "Backend & API",
    skills: [
      "api-design-rest",
      "api-security",
      "zod-validation",
      "auth-session",
      "rate-limiting",
      "background-jobs",
      "webhooks",
      "file-upload-security",
      "server-observability",
      "api-contracts",
    ],
  },
  {
    id: "database",
    label: "Database",
    skills: [
      "postgres-best-practices",
      "postgres-rls",
      "sql-performance",
      "database-migrations",
      "supabase-security",
      "prisma",
      "drizzle",
      "data-integrity",
      "transactions-locking",
      "audit-trails",
    ],
  },
  {
    id: "security",
    label: "Security",
    skills: [
      "security-review",
      "owasp-web",
      "secrets-detection",
      "npm-supply-chain",
      "vscode-extension-security",
      "xss-prevention",
      "csrf-protection",
      "auth-hardening",
      "input-validation",
      "secure-errors",
    ],
  },
  {
    id: "devops",
    label: "DevOps & CI/CD",
    skills: [
      "github-actions-ci",
      "docker",
      "deployment-checklist",
      "environment-variables",
      "linux-server-ops",
      "nginx-config",
      "aws-lightsail",
      "vercel-deployment",
      "monitoring-alerting",
      "release-management",
    ],
  },
  {
    id: "package",
    label: "Package & Open Source",
    skills: [
      "npm-package",
      "npm-publish-safety",
      "bun-package",
      "cli-tooling",
      "vscode-extension",
      "marketplace-readme",
      "open-source-readme",
      "changelog",
      "license-compliance",
      "contributor-guidelines",
    ],
  },
  {
    id: "ai-coding",
    label: "AI Coding Workflow",
    skills: [
      "agents-md",
      "claude-md",
      "cursor-rules",
      "copilot-instructions",
      "roo-rules",
      "codex-instructions",
      "prompt-engineering-code",
      "context-budgeting",
      "agent-task-planning",
      "agent-review-mode",
      "agent-debug-mode",
      "agent-security-mode",
    ],
  },
  {
    id: "frameworks",
    label: "Framework Specific",
    skills: [
      "nextjs",
      "nextjs-app-router",
      "react",
      "vite",
      "node-api",
      "express",
      "fastify",
      "nestjs",
      "sveltekit",
      "vue",
      "astro",
      "electron",
    ],
  },
  {
    id: "testing",
    label: "Testing",
    skills: [
      "vitest",
      "jest",
      "playwright",
      "cypress",
      "node-test",
      "testing-library",
      "mocking-strategy",
      "e2e-accessibility",
      "snapshot-testing",
      "regression-tests",
    ],
  },
  {
    id: "product-ux",
    label: "Product & UX",
    skills: [
      "ux-review",
      "empty-states",
      "onboarding-flow",
      "admin-dashboard-ux",
      "pricing-page",
      "landing-page",
      "seo-basics",
      "analytics-events",
      "conversion-optimization",
      "user-feedback-loop",
    ],
  },
  {
    id: "i18n",
    label: "i18n & Localization",
    skills: [
      "i18n-basics",
      "i18ntk",
      "translation-key-design",
      "locale-validation",
      "hardcoded-string-scan",
      "rtl-support",
      "pluralization",
      "date-number-formatting",
      "translation-expansion",
      "auto-translate-review",
    ],
  },
  {
    id: "prediction-market",
    label: "Prediction Market",
    skills: [
      "prediction-market-spec",
      "market-resolution-rules",
      "market-ambiguity-check",
      "duel-game-logic",
      "provably-fair-rng",
      "real-money-safety",
      "gaming-ui",
      "odds-pricing",
      "settlement-audit",
      "financial-copy-compliance",
    ],
  },
  {
    id: "maintenance",
    label: "Repository Maintenance",
    skills: [
      "repo-health-check",
      "dependency-updates",
      "dead-code-cleanup",
      "monorepo-management",
      "gitignore-hygiene",
      "package-json-audit",
      "commit-message-quality",
      "branching-strategy",
      "technical-debt-log",
      "architecture-decision-records",
    ],
  },
  {
    id: "advanced",
    label: "Advanced",
    skills: [
      "race-condition-review",
      "idempotency",
      "realtime-websocket",
      "cache-invalidation",
      "large-repo-navigation",
      "migration-safety",
      "api-rate-limit-design",
      "schema-versioning",
      "feature-flagging",
      "multi-tenant-safety",
    ],
  },
  {
    id: "full",
    label: "All Skills",
    skills: ["*"],
  },
];
